### ISSUE TITLE
Error when restoring database with java external function

### ISSUE THREAD

**Issue by artyom-smirnov** [FirebirdSQL/fbjava#8]
Database with single external java function can not be restored. Not sure if it engine's or plugin's problem. 

```
/opt/firebird/bin/gbak -user sysdba -password masterkey -rep /tmp/x.fbk localhost:/tmp/x_rest.fdb                                                              /workspace/fbjava
gbak: ERROR:java.lang.RuntimeException: java.sql.SQLException: database /tmp/x_rest.fdb shutdown [SQLState:HY000, ISC error code:335544528]
	at org.firebirdsql.fbjava.impl.ExternalEngine.lambda$open$3(ExternalEngine.java:1091)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.firebirdsql.fbjava.impl.ExternalEngine.open(ExternalEngine.java:1084)
	at org.firebirdsql.fbjava.impl.FbClientLibrary$IExternalEngine$VTable$1.invoke(FbClientLibrary.java:10228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)
Caused by: java.sql.SQLException: database /tmp/x_re...
gbak:Exiting before completion due to errors

```

**Comment by artyom-smirnov** [comment]
It's looks like plugin trying to connect to database, which not yet ready (because it restoring)
